Patroni на чистом RAFT

diff --git a/roles/dnscp/templates/dnscp.sh.j2 b/roles/dnscp/templates/dnscp.sh.j2
--- a/roles/dnscp/templates/dnscp.sh.j2
+++ b/roles/dnscp/templates/dnscp.sh.j2
@@ -7,7 +7,8 @@
 #
 # Thanks for the help Nikolay Mishchenko https://github.com/NickNeoOne
 
-### Script for multi-site Patroni clusters (version 01.06.2022)
+#v11082022
+### Script for multi-site Patroni clusters
 # * Uses Patroni callback
 # * VIP addresses can be from different subnets - one VIP address per subnet.
 # * Microsoft DNS Server and Active Directory Domain Services needed
@@ -60,14 +61,14 @@
 # Change only this variables
 #####################################################
 readonly VIPs="{{ cluster_vip }}" # VIP addresses (IPv4) in different subnets separated by commas, for client access to databases in the cluster
-readonly VCompName="{{ cluster_vcompname }}" # Virtual Computer Name - Client Access Point
-readonly VCompPassword="{{ cluster_vcomppassword }}" # Blank for non-secure update or set password for Virtual Computer Name account in Active Directory
-DNSzoneFQDN="{{ cluster_dnszonefqdn }}" # Set DNS zone FQDN (for example Microsoft AD DS Domain FQDN). Empty for automatically detect.
+readonly VCompName="{{ dnscp.vcompname }}" # Virtual Computer Name - Client Access Point
+readonly VCompPassword="{{ dnscp.vcomppassword }}" # Blank for non-secure update or set password for Virtual Computer Name account in Active Directory\SAMBA
+DNSzoneFQDN="{{ dnscp.dnszonefqdn }}" # Set DNS zone FQDN (for example Microsoft AD DS Domain FQDN). Empty for automatically detect.
 
 #####################################################
 # Other variables
 #####################################################
-DNSserver="{{ cluster_dnsserver }}" # Set FQDN or IP or empty (recommended for automatically detect). Used for register DNS name.
+DNSserver="{{ dnscp.dnsserver }}" # Set FQDN or IP or empty (recommended for automatically detect). Used for register DNS name.
 readonly SCRIPTNAME=$(echo $0 | awk -F"/" '{print $NF}')
 readonly SCRIPTPATH=$(dirname $0)
 readonly TTL=30 # DNS record TTL
@@ -77,7 +78,6 @@ readonly SCOPE=$3
 readonly LOGHEADER="Patroni Callback"
 MSG="[$LOGHEADER] Called: $0 <CB_NAME=$CB_NAME> <ROLE=$ROLE> <SCOPE=$SCOPE>"
 echo $MSG
-#logger $MSG
 
 #####################################################
 # Check prerequisites
@@ -86,12 +86,12 @@ echo $MSG
 if [[ "" == "$VIPs" ]]; then
     MSG="[$LOGHEADER] INFO: Check prerequisites: VIPs not defined. Nothing to do."
     echo $MSG
-    #logger $MSG
     exit 0; # Exit without error
 fi
 
-## Active Directory Domain joined? (check that the password is set and astra-winbind command exist)
+## Active Directory\SAMBA Domain joined? (check that the password is set and astra-winbind command exist)
 REQUIRED_PKG="astra-winbind"
+JOINED_OK=""
 if [[ ! -z $VCompPassword ]] && [[ "" != "$(dpkg-query -W --showformat='${Status}\n' $REQUIRED_PKG|grep "install ok installed")" ]]; then
     JOINED_OK=$(astra-winbind -i | awk '{print $NF}')
     if [[ "succeeded" == "$JOINED_OK" ]]; then
@@ -100,13 +100,10 @@ if [[ ! -z $VCompPassword ]] && [[ "" != "$(dpkg-query -W --showformat='${Status
             DNSzoneFQDN=$(astra-winbind -i | awk -F\" '{print $2}' | cut --complement --delimiter "." --fields 1)
             #MSG="[$LOGHEADER] INFO: Detected DNS zone FQDN is $DNSzoneFQDN"
             #echo $MSG
-            #logger $MSG
         fi
     else
-        MSG="[$LOGHEADER] ERROR: Check prerequisites: Not joined to Active Directory Domain!"
+        MSG="[$LOGHEADER] WARNING: Check prerequisites: Not joined to Active Directory\SAMBA Domain!"
         echo $MSG
-        #logger $MSG
-    exit 1; # Exit with error
     fi
     # $VCompPassword is empty. Script configured for non-secure DNS update.
 fi
@@ -115,26 +112,33 @@ fi
 REQUIRED_PKG="dnsutils"
 PKG_OK=$(dpkg-query -W --showformat='${Status}\n' $REQUIRED_PKG|grep "install ok installed")
 if [[ "" == "$PKG_OK" ]]; then
-    MSG="[$LOGHEADER] ERROR: Check prerequisites: No $REQUIRED_PKG."
+    MSG="[$LOGHEADER] WARNING: Check prerequisites: No $REQUIRED_PKG."
     echo $MSG
-    #logger $MSG
     #sudo apt-get --yes install $REQUIRED_PKG #Setting up $REQUIRED_PKG
     exit 1; # Exit with error
 else
     # Detect DNS Server
-    if [[ "" == "$DNSserver" ]]; then
+    if [[ "" == "$DNSserver" ]] && [[ "succeeded" == "$JOINED_OK" ]]; then
         # DNSserver=$(nslookup $(hostname).$DNSzoneFQDN | awk '/Server:/{gsub(/\/.*$/, "", $2); print $2}') # This is Primary DNS on network interface
         DNSserver=$(astra-winbind -i | awk -F\" '{print $2}') # AD DS logon DC
         #MSG="[$LOGHEADER] INFO: Detected DNS Server is $DNSserver"
         #echo $MSG
-        #logger $MSG
     fi
 fi
 
+# Set failsafe value
+if [[ "" == "$DNSserver" ]] && [[ "" != "$DNSzoneFQDN" ]]; then
+    DNSserver=$DNSzoneFQDN
+fi
+
+# Last check
 if [[ "" == "$DNSzoneFQDN" ]] || [[ "" == "$DNSserver" ]] || [[ "" == "$VCompName" ]]; then
-    MSG="[$LOGHEADER] INFO: Not all DNS options are set. Only VIPS wil be managed."
+    MSG=""; MSGSEPARATOR="";
+    if [[ "" == "$DNSzoneFQDN" ]]; then MSG="$MSG${MSGSEPARATOR}DNSzoneFQDN"; MSGSEPARATOR=", "; fi
+    if [[ "" == "$DNSserver" ]]; then MSG="$MSG${MSGSEPARATOR}DNSserver"; MSGSEPARATOR=", "; fi
+    if [[ "" == "$VCompName" ]]; then MSG="$MSG${MSGSEPARATOR}$MSGVCompName"; MSGSEPARATOR=", "; fi
+    MSG="[$LOGHEADER] INFO: DNSCP does not know about $MSG. Only VIPs wil be managed."
     echo $MSG
-    #logger $MSG
 fi
 
 readonly VCompNameFQDN=$VCompName.$DNSzoneFQDN
@@ -218,14 +222,12 @@ done
 if [[ -z $VIP ]]; then
 	MSG="[$LOGHEADER] WARNING: No suitable VIP ($VIPs) for $NETWORK"
 	echo $MSG
-    #logger $MSG
 else
 	#####################################################
 	# VIP
 	#####################################################
 	#MSG="[$LOGHEADER] INFO: VIP $VIP is candidate for current network"
 	#echo $MSG
-	#logger $MSG
 	case $CB_NAME in
 		on_stop )
 			#####################################################
@@ -237,16 +239,13 @@ else
 				if [[ $EXITCODE -eq 0 ]]; then
 					MSG="[$LOGHEADER] INFO: Deleting VIP $VIP by Patroni $CB_NAME callback SUCCEEDED"
 					echo $MSG
-					#logger $MSG
 				else
 					MSG="[$LOGHEADER] ERROR: Deleting VIP $VIP by Patroni $CB_NAME callback is FAILED with error code $EXITCODE."
 					echo $MSG
-					#logger $MSG
 				fi
 			else
 				MSG="[$LOGHEADER] INFO: VIP $VIP not exist, no action required.";
 				#echo $MSG
-				#logger $MSG
 			fi
 			;;
 		on_start|on_role_change )
@@ -260,16 +259,13 @@ else
 					if [[ $EXITCODE -eq 0 ]]; then
 						MSG="[$LOGHEADER] INFO: Adding VIP $VIP by Patroni $CB_NAME callback SUCCEEDED"
 						echo $MSG
-						#logger $MSG
 					else
 						MSG="[$LOGHEADER] ERROR: Adding VIP $VIP by Patroni $CB_NAME callback is FAILED with error code $EXITCODE."
 						echo $MSG
-						#logger $MSG
 					fi
 				else
 					MSG="[$LOGHEADER] INFO: VIP $VIP already present, no action required.";
 					#echo $MSG
-					#logger $MSG
 				fi
 				
 				#####################################################
@@ -291,35 +287,34 @@ else
 					)
 				
 					# Authentication by $VCompName Computer account
-					echo "$VCompPassword" | kinit $VCompName$ >/dev/null && KINITEXITCODE=$?
+					KINITEXITCODE=-1
+					if [[ "succeeded" == "$JOINED_OK" ]]; then
+						echo "$VCompPassword" | kinit $VCompName$ >/dev/null && KINITEXITCODE=$?
+					fi
 
 					# AddOrUpdateDNSRecord
 					if [[ ! -z $VCompPassword ]] && [[ $KINITEXITCODE -eq 0 ]]; then
-						# Active Directory authentication under Computer Account is success
+						# Active Directory\SAMBA authentication under Computer Account is success
 						# View received Kerberos tickets: klist
 						nsupdate -g -v <(echo "$NSDATA")
 						EXITCODE=$?;
 						if [[ $EXITCODE -eq 0 ]]; then
 							MSG="[$LOGHEADER] INFO: Registering $VCompNameFQDN on $DNSserver with secure DNS update SUCCEEDED"
 							echo $MSG
-							#logger $MSG
 						else
 							MSG="[$LOGHEADER] ERROR: Registering $VCompNameFQDN on $DNSserver with secure DNS update FAILED with error code $EXITCODE"
 							echo $MSG
-							#logger $MSG
 						fi
 					else
-						# Active Directory authentication is failed. Try to non-secure DNS-update.
+						# Active Directory\SAMBA authentication is failed. Try to non-secure DNS-update.
 						nsupdate -v <(echo "$NSDATA")
 						EXITCODE=$?;
 						if [[ $EXITCODE -eq 0 ]]; then
 							MSG="[$LOGHEADER] INFO: Registering $VCompNameFQDN on $DNSserver with non-secure DNS update SUCCEEDED"
 							echo $MSG
-							#logger $MSG
 						else
 							MSG="[$LOGHEADER] ERROR: Registering $VCompNameFQDN on $DNSserver with non-secure DNS update FAILED with error code $EXITCODE."
 							echo $MSG
-							#logger $MSG
 						fi
 					fi
 				fi
@@ -333,16 +328,13 @@ else
 					if [[ $EXITCODE -eq 0 ]]; then
 						MSG="[$LOGHEADER] INFO: Deleting VIP $VIP by Patroni $CB_NAME callback SUCCEEDED"
 						echo $MSG
-						#logger $MSG
 					else
 						MSG="[$LOGHEADER] ERROR: Deleting VIP $VIP by Patroni $CB_NAME callback is FAILED with error code $EXITCODE."
 						echo $MSG
-						#logger $MSG
 					fi
 				else
 					MSG="[$LOGHEADER] INFO: VIP $VIP not exist, no action required.";
 					#echo $MSG
-					#logger $MSG
 				fi
 			fi
 		;;
